#!/bin/bash

# Environment vars the user may set:
#   HPL_VERSION  – defaults to 2.3
#   HPL_ARCH     – e.g. inteloneapi
#   HPL_DIR      – path to hpl-VERSION
#   N, NB, P, Q  – problem size, block size, process grid

set -euo pipefail

HPL_VERSION="${HPL_VERSION:-2.3}"
HPL_DIR="${HPL_DIR:-$HOME/benchmarks/hpl/hpl-$HPL_VERSION}"
ARCH="${ARCH:-inteloneapi}"
NP="${HPL_NP:-$(nproc)}"

BIN_DIR="$HPL_DIR/bin/$ARCH"
mkdir -p "$BIN_DIR"
HPL_DAT="$BIN_DIR/HPL.dat"

# Try to pull current defaults from an existing HPL.dat for this ARCH
fN=""; fNB=""; fP=""; fQ=""
if [[ -f "$HPL_DAT" ]]; then
    fN="$(awk '$2=="Ns"{print $1; exit}'  "$HPL_DAT" || true)"
    fNB="$(awk '$2=="NBs"{print $1; exit}' "$HPL_DAT" || true)"
    fP="$(awk '$2=="Ps"{print $1; exit}'  "$HPL_DAT" || true)"
    fQ="$(awk '$2=="Qs"{print $1; exit}'  "$HPL_DAT" || true)"
fi

# Use env overrides if set; otherwise fall back to file values; otherwise hard defaults
N="${N:-${fN:-2048}}"
NB="${NB:-${fNB:-128}}"
P="${P:-${fP:-$NP}}"
Q="${Q:-${fQ:-1}}"

cat >"$HPL_DAT" <<EOF
HPL Linpack benchmark input file
Auto-generated by make_hpl_dat.sh
HPL.out      output file name (if any)
6            device out (6=stdout,7=stderr,file)
1            # of problem sizes (N)
$N           Ns
1            # of NBs
$NB          NBs
0            PMAP process mapping (0=Row-,1=Column-major)
1            # of process grids (P x Q)
$P           Ps
$Q           Qs
16.0         threshold
1            # of panel fact
2            PFACTs (0=left, 1=Crout, 2=Right)
1            # of recursive stopping criterium
4            NBMINs (>= 1)
1            # of panels in recursion
2            NDIVs
1            # of recursive panel fact.
2            RFACTs (0=left, 1=Crout, 2=Right)
1            # of broadcast
1            BCASTs (0=1rg,1=1rM,2=2rg,3=2rM,4=Lng,5=LnM)
1            # of lookahead depth
1            DEPTHs (>=0)
2            SWAP (0=bin-exch,1=long,2=mix)
64           swapping threshold
0            L1 in (0=transposed,1=no-transposed) form
0            U  in (0=transposed,1=no-transposed) form
1            Equilibration (0=no,1=yes)
8            memory alignment in double (> 0)
EOF

echo "Wrote $(realpath "$HPL_DAT")"
