#! This file will be preprocessed using the same preprocessor options as used
#! for the compilation and additionally setting OMP_THREADS to $(TEST_OMP_THREADS).

#:include 'common.fypp'
#! If under travis CI, avoid longer tests
#:set LONG_TEST = not defined('TRAVIS')

#{if MPI_PROCS <= 1}#C6H6_eigvec#{endif}#
#{if MPI_PROCS <= 1}#C6H6_ir#{endif}#
#{if MPI_PROCS <= 1}#C6H6#{endif}#
#{if MPI_PROCS <= 1}#C6H6_rr#{endif}#
#{if WITH_MAGMA}#C6H6_gpu#{endif}#
#{if MPI_PROCS <= 1}#C24O6H8#{endif}#
#{if MPI_PROCS <= 1}#C24O6H8_atoms#{endif}#
#{if MPI_PROCS <= 1}#C24O6H8_extfile#{endif}#
#{if MPI_PROCS <= 1}#C24O6H8_select#{endif}#
