# CMake generated Testfile for 
# Source directory: /home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes
# Build directory: /home/witsa/AutomationScripts/dftbplus/_build/test/app/modes
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(app/modes/C6H6_eigvec "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/bin/autotest2" "-r" "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes" "-w" "/home/witsa/AutomationScripts/dftbplus/_build/test/app/modes" "-d" "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/bin/tagdiff" "-P" "" "-p" "/home/witsa/AutomationScripts/dftbplus/_build/app/modes/modes" "-s" "P,R,C,S" "C6H6_eigvec")
set_tests_properties(app/modes/C6H6_eigvec PROPERTIES  ENVIRONMENT "DFTBPLUS_PARAM_DIR=/home/witsa/AutomationScripts/dftbplus/dftbplus/external" _BACKTRACE_TRIPLES "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/CMakeLists.txt;28;add_test;/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/CMakeLists.txt;0;")
add_test(app/modes/C6H6_ir "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/bin/autotest2" "-r" "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes" "-w" "/home/witsa/AutomationScripts/dftbplus/_build/test/app/modes" "-d" "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/bin/tagdiff" "-P" "" "-p" "/home/witsa/AutomationScripts/dftbplus/_build/app/modes/modes" "-s" "P,R,C,S" "C6H6_ir")
set_tests_properties(app/modes/C6H6_ir PROPERTIES  ENVIRONMENT "DFTBPLUS_PARAM_DIR=/home/witsa/AutomationScripts/dftbplus/dftbplus/external" _BACKTRACE_TRIPLES "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/CMakeLists.txt;28;add_test;/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/CMakeLists.txt;0;")
add_test(app/modes/C6H6 "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/bin/autotest2" "-r" "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes" "-w" "/home/witsa/AutomationScripts/dftbplus/_build/test/app/modes" "-d" "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/bin/tagdiff" "-P" "" "-p" "/home/witsa/AutomationScripts/dftbplus/_build/app/modes/modes" "-s" "P,R,C,S" "C6H6")
set_tests_properties(app/modes/C6H6 PROPERTIES  ENVIRONMENT "DFTBPLUS_PARAM_DIR=/home/witsa/AutomationScripts/dftbplus/dftbplus/external" _BACKTRACE_TRIPLES "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/CMakeLists.txt;28;add_test;/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/CMakeLists.txt;0;")
add_test(app/modes/C6H6_rr "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/bin/autotest2" "-r" "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes" "-w" "/home/witsa/AutomationScripts/dftbplus/_build/test/app/modes" "-d" "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/bin/tagdiff" "-P" "" "-p" "/home/witsa/AutomationScripts/dftbplus/_build/app/modes/modes" "-s" "P,R,C,S" "C6H6_rr")
set_tests_properties(app/modes/C6H6_rr PROPERTIES  ENVIRONMENT "DFTBPLUS_PARAM_DIR=/home/witsa/AutomationScripts/dftbplus/dftbplus/external" _BACKTRACE_TRIPLES "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/CMakeLists.txt;28;add_test;/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/CMakeLists.txt;0;")
add_test(app/modes/C24O6H8 "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/bin/autotest2" "-r" "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes" "-w" "/home/witsa/AutomationScripts/dftbplus/_build/test/app/modes" "-d" "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/bin/tagdiff" "-P" "" "-p" "/home/witsa/AutomationScripts/dftbplus/_build/app/modes/modes" "-s" "P,R,C,S" "C24O6H8")
set_tests_properties(app/modes/C24O6H8 PROPERTIES  ENVIRONMENT "DFTBPLUS_PARAM_DIR=/home/witsa/AutomationScripts/dftbplus/dftbplus/external" _BACKTRACE_TRIPLES "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/CMakeLists.txt;28;add_test;/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/CMakeLists.txt;0;")
add_test(app/modes/C24O6H8_atoms "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/bin/autotest2" "-r" "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes" "-w" "/home/witsa/AutomationScripts/dftbplus/_build/test/app/modes" "-d" "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/bin/tagdiff" "-P" "" "-p" "/home/witsa/AutomationScripts/dftbplus/_build/app/modes/modes" "-s" "P,R,C,S" "C24O6H8_atoms")
set_tests_properties(app/modes/C24O6H8_atoms PROPERTIES  ENVIRONMENT "DFTBPLUS_PARAM_DIR=/home/witsa/AutomationScripts/dftbplus/dftbplus/external" _BACKTRACE_TRIPLES "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/CMakeLists.txt;28;add_test;/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/CMakeLists.txt;0;")
add_test(app/modes/C24O6H8_extfile "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/bin/autotest2" "-r" "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes" "-w" "/home/witsa/AutomationScripts/dftbplus/_build/test/app/modes" "-d" "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/bin/tagdiff" "-P" "" "-p" "/home/witsa/AutomationScripts/dftbplus/_build/app/modes/modes" "-s" "P,R,C,S" "C24O6H8_extfile")
set_tests_properties(app/modes/C24O6H8_extfile PROPERTIES  ENVIRONMENT "DFTBPLUS_PARAM_DIR=/home/witsa/AutomationScripts/dftbplus/dftbplus/external" _BACKTRACE_TRIPLES "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/CMakeLists.txt;28;add_test;/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/CMakeLists.txt;0;")
add_test(app/modes/C24O6H8_select "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/bin/autotest2" "-r" "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes" "-w" "/home/witsa/AutomationScripts/dftbplus/_build/test/app/modes" "-d" "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/bin/tagdiff" "-P" "" "-p" "/home/witsa/AutomationScripts/dftbplus/_build/app/modes/modes" "-s" "P,R,C,S" "C24O6H8_select")
set_tests_properties(app/modes/C24O6H8_select PROPERTIES  ENVIRONMENT "DFTBPLUS_PARAM_DIR=/home/witsa/AutomationScripts/dftbplus/dftbplus/external" _BACKTRACE_TRIPLES "/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/CMakeLists.txt;28;add_test;/home/witsa/AutomationScripts/dftbplus/dftbplus/test/app/modes/CMakeLists.txt;0;")
