#! This file will be preprocessed using the same preprocessor options as used
#! for the compilation and additionally setting MPI_PROCS equal to the make variable
#! $(TEST_MPI_PROCS) and OMP_THREADS to $(TEST_OMP_THREADS).

#:include 'common.fypp'

#{if not WITH_MPI}#extcharges#{endif}#
#{if not WITH_MPI}#extpot#{endif}#
#{if not WITH_MPI}#extpot2#{endif}#
#{if not WITH_MPI}#extefield#{endif}#
#{if not WITH_MPI}#timeprop#{endif}#
#{if not WITH_MPI}#ehrenfest#{endif}#
#{if not WITH_MPI}#ehrenfest_ext_ions#{endif}#
#{if not WITH_MPI}#fileinit#{endif}#
#{if not WITH_MPI and defined('WITH_C_EXECUTABLES')}#fileinitc#{endif}#
#{if not WITH_MPI}#qdepextpot#{endif}#
#{if not WITH_MPI and defined('WITH_C_EXECUTABLES')}#qdepextpotc#{endif}#
#! The next test fails on 1 MPI proc with NAG compiler and -nan flag:
#{if not WITH_MPI or (MPI_PROCS > 1 and MPI_PROCS <= 8)}#resetspecies_NaCl#{endif}#
#{if MPI_PROCS <= 4}#resetspecies_C2H6#{endif}#
#{if not WITH_MPI}#treeinit#{endif}#
#{if WITH_MPI and (MPI_PROCS % 4 == 0) and MPI_PROCS <= 4}#mpisubgrids#{endif}#
#{if not WITH_MPI}#neighbour_list#{endif}#
#{if not WITH_MPI and defined('WITH_C_EXECUTABLES')}#neighbour_list_c#{endif}#
#{if not WITH_MPI}#intcharges#{endif}#
#{if WITH_MPI and (MPI_PROCS % 2 == 0) and MPI_PROCS <= 4 and defined('WITH_C_EXECUTABLES')}#mpi_intcharges_c#{endif}#
